"""Domain primitives for the sovereign SKHarness Evolution Arena.

Domain contracts remain usable across process boundaries; the explicit runner module
composes them with the production Pi sandbox without weakening verifier isolation.
"""

from skharness.arena.access import (
    AccessDeniedError,
    AgentMessage,
    AttemptOwnership,
    CollaborationAccess,
)
from skharness.arena.collaboration import (
    CollaborationError,
    ExperimentCatalog,
    ExperimentMatch,
    NegativeKind,
    NegativeKnowledge,
    NegativeKnowledgeIndex,
    PositiveEvidence,
    RefinementEvent,
    RefinementEvidenceKind,
    RefinementJournal,
    RefinementProposal,
    RefinementScope,
    RefinementState,
    RefinementTargetKind,
    evidence_id,
)
from skharness.arena.lineage import LineageGraph
from skharness.arena.memory_adapter import (
    ExecutableRuntimeBackend,
    MemoryReceipt,
    RuntimeSKMemoryAdapter,
)
from skharness.arena.metrics import (
    MetricDirection,
    MetricObjective,
    MetricSummary,
    ParetoCandidate,
    VerifiedParetoCandidate,
    pareto_frontier,
    summarize,
    verified_pareto_frontier,
)
from skharness.arena.models import (
    ChallengeSpec,
    Experiment,
    ExperimentEvent,
    ExperimentState,
    Measurement,
    Result,
    VerificationState,
    canonical_digest,
)
from skharness.arena.operations import ArenaJobService
from skharness.arena.runner import (
    PiExperimentRunner,
    RunOutcome,
    SandboxProcessSupervisor,
    TaskDisposition,
    build_production_pi_runner,
    pi_launch_spec,
)
from skharness.arena.status import ArenaStatusService, BoundedArenaMetrics, ProbeResult
from skharness.arena.store import ArenaStore, CorruptEventLogError, EventConflictError
from skharness.arena.swarm import (
    A2AEvent,
    A2AEventKind,
    BudgetExceededError,
    BudgetUsage,
    ExecutionBudget,
    SubagentContract,
    SubagentDisposition,
    SubagentResult,
    SwarmContractError,
    SwarmIdentity,
    SwarmRole,
    TeamBudget,
    TeamBudgetLedger,
    TeamBudgetSnapshot,
)
from skharness.arena.swarm_control import (
    SwarmAdmission,
    SwarmAdmissionReason,
    SwarmScheduler,
    SwarmStateError,
    WorkerLease,
    WorkerLeaseState,
)
from skharness.arena.swarm_orchestrator import (
    A2AJournal,
    SwarmPhase,
    SwarmRunReport,
    SwarmTopology,
    SwarmTopologyPolicy,
    TrustedSwarmOrchestrator,
    WorkerExecution,
)
from skharness.arena.swarm_pi import PiSwarmLaunch, PiSwarmWorkerRuntime
from skharness.arena.swarm_verifier import (
    CheckProvenance,
    CompletionDecision,
    CriterionEvidence,
    EvidenceSource,
    SwarmCompletionGate,
    VerifierAttestation,
    VerifierVerdict,
)
from skharness.arena.trajectory import (
    CardSize,
    EvidenceModelRouter,
    ModelTrial,
    PhaseBudget,
    UnqualifiedRouteError,
    compact_pi_events,
)
from skharness.arena.verifier import (
    ControlKind,
    IndependentVerifier,
    PrivateEvaluationHandle,
    ProvisionalSubmission,
    TrialEvidence,
    VerificationPolicy,
    VerificationStatus,
    VerificationVerdict,
)
from skharness.arena.verifier_boundary import IsolatedVerifierBoundary

__all__ = [
    "ArenaStore",
    "A2AJournal",
    "A2AEvent",
    "A2AEventKind",
    "AccessDeniedError",
    "AgentMessage",
    "AttemptOwnership",
    "ArenaStatusService",
    "ArenaJobService",
    "BoundedArenaMetrics",
    "BudgetExceededError",
    "BudgetUsage",
    "CollaborationError",
    "CollaborationAccess",
    "ChallengeSpec",
    "CheckProvenance",
    "CardSize",
    "ControlKind",
    "CompletionDecision",
    "CorruptEventLogError",
    "CriterionEvidence",
    "EvidenceSource",
    "EventConflictError",
    "Experiment",
    "EvidenceModelRouter",
    "ExperimentCatalog",
    "ExperimentMatch",
    "ExperimentEvent",
    "ExperimentState",
    "ExecutableRuntimeBackend",
    "ExecutionBudget",
    "IndependentVerifier",
    "IsolatedVerifierBoundary",
    "LineageGraph",
    "Measurement",
    "ModelTrial",
    "MetricDirection",
    "MetricObjective",
    "MetricSummary",
    "NegativeKind",
    "NegativeKnowledge",
    "NegativeKnowledgeIndex",
    "PositiveEvidence",
    "ParetoCandidate",
    "VerifiedParetoCandidate",
    "PrivateEvaluationHandle",
    "PiExperimentRunner",
    "PiSwarmLaunch",
    "PiSwarmWorkerRuntime",
    "PhaseBudget",
    "ProbeResult",
    "ProvisionalSubmission",
    "Result",
    "RunOutcome",
    "MemoryReceipt",
    "RuntimeSKMemoryAdapter",
    "SandboxProcessSupervisor",
    "SubagentContract",
    "SubagentDisposition",
    "SubagentResult",
    "SwarmAdmission",
    "SwarmAdmissionReason",
    "SwarmContractError",
    "SwarmCompletionGate",
    "SwarmPhase",
    "SwarmRunReport",
    "SwarmTopology",
    "SwarmTopologyPolicy",
    "SwarmIdentity",
    "SwarmRole",
    "SwarmScheduler",
    "SwarmStateError",
    "TeamBudget",
    "TeamBudgetLedger",
    "TeamBudgetSnapshot",
    "TaskDisposition",
    "TrustedSwarmOrchestrator",
    "RefinementEvent",
    "RefinementEvidenceKind",
    "RefinementJournal",
    "RefinementProposal",
    "RefinementScope",
    "RefinementState",
    "RefinementTargetKind",
    "TrialEvidence",
    "VerificationPolicy",
    "VerificationStatus",
    "VerificationState",
    "VerificationVerdict",
    "VerifierAttestation",
    "VerifierVerdict",
    "WorkerExecution",
    "WorkerLease",
    "WorkerLeaseState",
    "UnqualifiedRouteError",
    "build_production_pi_runner",
    "pareto_frontier",
    "pi_launch_spec",
    "canonical_digest",
    "compact_pi_events",
    "evidence_id",
    "summarize",
    "verified_pareto_frontier",
]
